const fs=require('fs'),path=require('path');
const root=__dirname, pub=path.join(root,'public');
const css=fs.readFileSync(path.join(pub,'viewer.css'),'utf8');
const fragment=fs.readFileSync(path.join(pub,'model-fragment.html'),'utf8');
const offline=fragment.replace('https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js','three.min.js');
const html='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>五层堡垒 · 交互三维模型</title><style>'+css+'\nbody{margin:0;padding:16px;background:var(--background);color:var(--foreground);font-family:system-ui,Microsoft YaHei,sans-serif}</style></head><body>'+offline+'</body></html>';
fs.writeFileSync(path.join(pub,'model.html'),html);
const offlineDir=path.join(root,'..','bunker-3d-offline');fs.mkdirSync(offlineDir,{recursive:true});
fs.writeFileSync(path.join(offlineDir,'打开三维堡垒.html'),html);
fs.copyFileSync(path.join(pub,'three.min.js'),path.join(offlineDir,'three.min.js'));
fs.writeFileSync(path.join(offlineDir,'使用说明.txt'),'双击“打开三维堡垒.html”，使用支持 WebGL 的现代浏览器，无需联网。\n鼠标左键拖动旋转，滚轮缩放，右键拖动平移。触屏单指旋转、双指缩放。方向键旋转，加减键缩放。\n选择整体或 B1–B5；楼层展开用于查看内部；点击房间或用下拉框选择房间，再点“聚焦所选空间”。双击房间也可聚焦。\nB1 无人机间位于重卡库与总控室之间，内设独立枪械储存隔间；B4 维修工坊也有一处。柜内只有外形展示，无内部构造。\n加厚顶部岩层，延长折线车道；黄色路线从无人机间经专用通道和货运升降段抵达室外起降点。岩层尺度为未标定示意，楼层展开间距不代表埋深。\n保存当前视角导出无文字标注的模型截图。导出 OBJ 保存当前可见部分，同时下载 MTL，保留分组名称与柜门透明度；若浏览器限制连续下载，请允许多文件下载。两个文件应放在同一目录。\n随包提供整体合层状态的 bunker.obj 和 bunker.mtl，可导入 Blender 等建模软件。\n模型为简化几何空间概念，不是精确复刻效果图。比例、埋深和容量未经核算，不可直接用于施工。\n');
fs.appendFileSync(path.join(offlineDir,'使用说明.txt'),'\n新增交互：进入第一人称后，拖动画面转头，WASD/方向键移动；手机使用画面下方的移动按钮。移动受墙体和主要设备阻挡，漫游范围为室内房间与走廊；上下层通过电梯定位切换。Escape 或退出按钮返回剖面。\n点击单件物品或使用物品下拉框，选择替换款式和配色，再点应用替换。近看物品可聚焦；恢复此物品可撤销该件修改。替换保存在本浏览器，不同步至其他设备。OBJ 导出包含当前替换。\n重卡库与无人机间加入实体隔墙和可开合门组，可点门或开合车库隔断门按钮查看；防爆等级未核算。\n');
fs.appendFileSync(path.join(offlineDir,'使用说明.txt'),'\n本次改造：B1 九车位车辆库（4辆重卡、2辆轻型及3辆重型越野车），总控与生活区共墙并由单人门直接连通，生活区收回前方走道面积。B4 仓储加深至原来的约2.38倍，四类仓储共108架；未换算成200年有效供给。初始合层显示，楼层展开可用于拆解查看。\n');
fs.appendFileSync(path.join(offlineDir,'使用说明.txt'),'\n连接修正：折线车道从车库左侧独立车辆门进入，整体和B1均显示车道；无人机室的公共通道、专用转运通道出口及转运通道进入货运升降机处设置隔离门。点击隔离门可开合，室内漫游靠近时自动开启，离开后关闭。\n');
fs.appendFileSync(path.join(offlineDir,'使用说明.txt'),'\n游戏交互：WASD移动；驾驶时W/S油门或倒车、A/D转向，空格刹车，F下车。先选择车辆再驾驶；后排越野车从车库左侧调度带绕出。E手动开常闭门或拿起近处物品，Q放下；游戏枪械左键射击，R换弹，B2训练区有靶标。可以点击锁定鼠标，也可拖动转头。\n电梯需走进轿厢后使用上一层/下一层；货运升降机同样在轿厢内操作，往返B1与地面。B1-B5两处楼梯可连续行走，卧室直接接入短应急连接。起降井植被盖板可开合。车辆改装选择防护外观、越野轮胎、补给架、辅助灯并应用，保存到当前浏览器。\n驾驶、枪械与射击均为虚构的轻量游戏模拟，非真实车辆或防弹工程性能。\n');
console.log('Standalone and offline viewer built.');
