const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const events=new Map(),elements=new Map(),downloads=[],blobs=new Map();
function element(id=''){const el={id,style:{},dataset:{},value:'',checked:false,hidden:false,clientWidth:1440,clientHeight:650,children:[],options:[],textContent:'',addEventListener(type,fn){events.set(id+':'+type,fn)},append(child){this.children.push(child);if(id==='room-select')this.options.push(child)},setAttribute(k,v){this[k]=v},focus(){},setPointerCapture(){},getBoundingClientRect(){return {left:0,top:0,width:1440,height:650}},click(){if(this.download)downloads.push({name:this.download,blob:blobs.get(this.href)})},toDataURL(){return 'data:image/png;base64,'}};return el;}
for(const id of ['bunker-viewer','model-canvas','model-stage','model-labels','model-message','room-select','room-detail','gap','gap-value','rock','labels','route','home','top','focus-room','export-model','export-image','walk-toggle','walk-up','walk-down','walk-status','walk-pad','item-select','item-inspector','item-title','item-description','item-variant','item-color','item-apply','item-reset','item-focus','item-save-status','blast-door'])elements.set(id,element(id));
elements.get('item-variant').options=[element(),element()];
elements.get('labels').checked=true;elements.get('route').checked=true;elements.get('rock').checked=true;elements.get('gap').value='6';
const buttons=['all','0','1','2','3','4'].map(f=>{const el=element('floor-'+f);el.dataset.floor=f;return el});
const root=elements.get('bunker-viewer');root.querySelector=s=>elements.get(s.slice(1));root.querySelectorAll=s=>s==='[data-floor]'?buttons:[];
const storage=new Map();const ctx={console,Blob,devicePixelRatio:1,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},addEventListener:(k,fn)=>events.set('window:'+k,fn),setTimeout:fn=>fn(),requestAnimationFrame(){},matchMedia:()=>({matches:false,addEventListener(){}}),ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},URL:{createObjectURL(blob){const key='blob:'+blobs.size;blobs.set(key,blob);return key},revokeObjectURL(){}},document:{getElementById:id=>elements.get(id),createElement:()=>element()}};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/three.min.js'),'utf8'),ctx);
ctx.THREE.WebGLRenderer=class{setPixelRatio(){}setSize(){}render(){}};
const html=fs.readFileSync(path.join(__dirname,'../public/model-fragment.html'),'utf8');
const code=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];
vm.runInContext(code,ctx,{timeout:15000});
const model=ctx.bunkerModel;assert(model,'model initialized');assert.equal(model.floors.length,5);assert(model.rooms.length>=20);
const counts={trucks:0,generators:0,firearmAlcoves:0,storedSilhouettes:0,vehicleGates:0};model.model.traverse(o=>{if(o.name==='heavy-truck')counts.trucks++;if(o.name==='generator')counts.generators++;if(o.name==='firearm-storage-alcove'){counts.firearmAlcoves++;assert(['独立无人机间','维修工坊'].includes(model.rooms[Number(o.parent.userData.room)].name));}if(o.name==='stored-firearm-silhouette')counts.storedSilhouettes++;if(o.name==='vehicle-isolation-gate')counts.vehicleGates++;});assert.equal(counts.trucks,4);assert.equal(counts.generators,10);assert.equal(counts.firearmAlcoves,2);assert.equal(counts.storedSilhouettes,8);assert.equal(counts.vehicleGates,4);assert.equal(model.state.coverDepth,32);assert.equal(model.model.getObjectByName('thick-rock-cap').scale.y,32);assert(model.model.getObjectByName('drone-surface-lift'));
model.setFloor('0');assert.deepEqual(Array.from(model.floors,f=>f.visible),[true,false,false,false,false]);
const drone=model.rooms.find(r=>r.name==='独立无人机间'),garage=model.rooms.find(r=>r.name==='九车位车辆库'),control=model.rooms.find(r=>r.name==='总监控室');assert.equal(drone.floor,0);assert(garage.x<drone.x&&drone.x<control.x);
model.setSelection(drone.id);assert(elements.get('room-detail').textContent.includes('室外起降点'));
events.get('focus-room:click')();assert.equal(model.state.mode,'0');assert(model.state.radius<50);
elements.get('gap').value='12';events.get('gap:input')({target:elements.get('gap')});assert.equal(model.state.gap,12);assert.equal(model.floors[0].position.y,84);
events.get('model-canvas:keydown')({key:'ArrowRight',preventDefault(){}});assert(model.state.theta>.3);
events.get('model-canvas:wheel')({deltaY:-100,preventDefault(){}});assert(model.state.radius<280);
elements.get('route').checked=false;events.get('route:change')();assert.equal(model.model.getObjectByName('drone-transfer-route').visible,false);
elements.get('route').checked=true;elements.get('gap').value='0';events.get('gap:input')({target:elements.get('gap')});model.setFloor('all');model.setSelection('');
assert(model.items.length>100,'individual item catalog');
assert(model.model.getObjectByName('garage-drone-blast-partition'),'solid separation between garage and drone room');
model.setSelection(drone.id);model.enterWalk();assert(model.state.walking);assert.equal(model.state.gap,0);assert.equal(model.state.walkFloor,0);assert.equal(elements.get('gap').disabled,true);
const before=model.state.walkPosition.z;model.moveWalk(0,-1);assert(model.state.walkPosition.z<before,'walks forward');model.moveWalk(200,0);assert(model.state.walkPosition.x<62,'cannot leave floor edge');model.moveWalk(0,100);assert(model.state.walkPosition.z<27,'cannot walk through perimeter');
model.changeWalkFloor(4);assert.equal(model.state.walkFloor,4);assert.equal(model.state.walkPosition.y,1.75);
assert(!model.canWalk(-49,-8,4),'tank blocks player');
model.exitWalk();assert(!model.state.walking);assert.equal(elements.get('gap').disabled,false);
model.setFloor('all');model.rebuildColliders();
for(const room of model.rooms){if(room.name==='单人生活区')continue;assert(model.canWalk(room.x,13.5,room.floor),room.name+' hallway access');assert(model.canWalk(room.x,11,room.floor),room.name+' front doorway');}
assert(model.canWalk(-7,-2,0),'garage-drone partition portal connects');assert(!model.canWalk(-7,-8,0),'partition blocks elsewhere');
events.get('blast-door:click')();model.animateDoors(.2);assert.equal(model.doors.find(d=>d.blast).open,1);events.get('blast-door:click')();model.animateDoors(.2);assert.equal(model.doors.find(d=>d.blast).open,0);
const living=model.rooms.find(r=>r.name==='单人生活区');
assert.equal(control.x+control.w/2,living.x-living.w/2,'shared wall without corridor gap');
assert(model.model.getObjectByName('control-living-single-blast-door'));
for(const x of [32.4,33,33.6])assert(model.canWalk(x,3,0),'walk through direct control-living doorway');
assert(!model.canWalk(33,-4,0),'shared wall blocks except doorway');
assert.equal(model.items.filter(i=>i.group.name==='light-offroad').length,2);
assert.equal(model.items.filter(i=>i.group.name==='heavy-offroad').length,3);
const warehouses=model.rooms.filter(r=>r.floor===3&&r.name!=='维修工坊');
assert.equal(warehouses.reduce((n,r)=>n+model.items.filter(i=>i.roomId===r.id&&i.type==='shelf').length,0),108);
assert(warehouses.every(r=>r.d===62),'storage footprint expanded');
assert(model.canWalk(-46,-53,3),'expanded rear service gallery reachable');
assert(model.canWalk(-30.5,-35,0),'expanded garage gallery reachable');
const suv=model.items.find(i=>i.type==='offroad');model.replaceItem(suv,1,'olive');assert(suv.extra);model.replaceItem(suv,0,'original');assert.equal(suv.extra,null);
const access=model.model.getObjectByName('arrival-and-drone-route');model.setFloor('0');assert(access.visible,'road visible in B1');
const segments=[];access.traverse(o=>{if(o.name==='vehicle-road-segment')segments.push(o)});
assert.equal(segments.length,4);
for(const segment of segments){const b=new ctx.THREE.Box3().setFromObject(segment);assert(b.max.x<=garage.x-garage.w/2+.001,'road stays outside garage footprint');}
assert.equal(model.model.getObjectByName('garage-side-vehicle-door').scale.y,1.8,'truck doorway has vehicle clearance');for(const o of model.floors[0].children){if(!o.isMesh)continue;const b=new ctx.THREE.Box3().setFromObject(o);const base=model.floors[0].position.y;if(b.max.y-base>.42&&b.min.y-base<2.5)assert(!(b.min.x<3.77&&b.max.x>3.23&&b.min.z<-18.43&&b.max.z>-18.97),'floor boundary wall preserves drone passage');}
for(const name of ['drone-public-isolation-door','drone-transfer-isolation-door','transfer-lift-isolation-door']){const frame=model.model.getObjectByName(name);assert(frame?.userData.isolation,name);model.toggleIsolationDoor(name);model.animateDoors(.2);assert.equal(model.doors.find(d=>d.frame===frame).open,1);model.toggleIsolationDoor(name);model.animateDoors(.2);assert.equal(model.doors.find(d=>d.frame===frame).open,0);}
model.setFloor('all');model.rebuildColliders();assert(model.canWalk(3.5,-16,0),'drone transfer threshold');assert(model.canWalk(3.5,-39,0),'transfer corridor turn');assert(model.canWalk(-63,-40,0),'lift isolation threshold');assert(!model.canWalk(-63,-38,0),'lift partition solid beside door');assert(model.canWalk(-68,-40,0),'cargo lift entrance');
const truckItem=model.items.find(i=>i.type==='truck'),otherTruck=model.items.filter(i=>i.type==='truck')[1];
const otherMaterial=otherTruck.group.children.find(o=>o.isMesh).material;
model.selectItem(truckItem.id);model.replaceItem(truckItem,1,'slate');assert.equal(truckItem.cargo.visible,false);assert.equal(truckItem.variant,1);assert.equal(otherTruck.group.children.find(o=>o.isMesh).material,otherMaterial,'replacement isolated to one item');assert(storage.get('bunker-item-edits-v1').includes('slate'));
model.replaceItem(truckItem,0,'original');assert(truckItem.cargo.visible);assert.equal(truckItem.extra,null);
const tankItem=model.items.find(i=>i.type==='tank'),tankOriginal=tankItem.group.geometry;model.replaceItem(tankItem,1,'original');assert.notEqual(tankItem.group.geometry,tankOriginal);model.replaceItem(tankItem,0,'original');assert.equal(tankItem.group.geometry,tankOriginal);
model.selectItem('');model.setSelection('');model.setFloor('all');
events.get('export-model:click')();assert.equal(downloads.length,2);assert(downloads[0].name==='bunker.obj');
(async()=>{const out=path.join(__dirname,'../../bunker-3d-offline');for(const download of downloads){const text=await download.blob.text();assert(text.length>500);assert(!text.includes('NaN'));if(download.name.endsWith('.mtl'))assert(text.includes('d 0.16'));fs.writeFileSync(path.join(out,download.name),text);}console.log(JSON.stringify({status:'pass',floors:5,rooms:model.rooms.length,inspectableItems:model.items.length,...counts,lightOffroads:2,heavyOffroads:3,warehouseShelves:108,checked:['initialization','B1 drone adjacency','vehicle road outside garage footprint','road visible in B1','three drone route isolation doors and animation','transfer corridor and cargo lift entry collision','two storage alcoves','deeper rock cap','surface cargo lift','four vehicle gates','room focus','single floor visibility','room selection','floor spread','keyboard orbit','wheel zoom','route visibility','OBJ+MTL export with transparency','first-person movement and floor change','wall and equipment collision','all front doorways accessible','blast partition and door animation','individual item replacement and reset','device-local item persistence'],limitation:'This script mocks the DOM and renderer; actual WebGL render is checked separately in headless Chrome.'},null,2));})().catch(e=>{console.error(e);process.exitCode=1});
